# first_paper results
FIRST_PAPER_LOCAL_RESULTS=results_first_paper_local_clean.yaml
FIRST_PAPER_DATA_RELEASE_DIR=first_paper_data_release
FIRST_PAPER_PP_TEST_OUTDIR=basic_bbh/outdir_aspire_precessing_spins_XPHM/