# first_paper results
FIRST_PAPER_LOCAL_RESULTS=results_first_paper_local_clean.yaml
FIRST_PAPER_ASPIRE_CHECKPOINT=/users/mjwill/git_repos/aspire-analyses/gw/real_data/GW150914/outdir_GW150914_XO4a_aspire_from_dynesty_importance_sampling_B/result/aspire_checkpoint.h5
FIRST_PAPER_DATA_RELEASE_DIR=first_paper_data_release
FIRST_PAPER_PP_TEST_OUTDIR=basic_bbh/outdir_aspire_precessing_spins_XPHM/
FIRST_PAPER_ZENODO_DOI=17514969
